image: node:12.15

pipelines:
  pull-requests:
    '**':
      - step:
          name: Install & Test
          caches:
            - node
          script:
            - mv .npmrc_config .npmrc
            - npm ci
            - npm test
  tags:
    '**':
      - step:
          name: Install & Test
          caches:
            - node
          script:
            - mv .npmrc_config .npmrc
            - npm ci
            - npm test
      - step:
          name: Publish to NPM
          deployment: production
          script:
            - mv .npmrc_config .npmrc
            - npm publish
  branches:
    master:
      - step:
          name: Install & Test
          caches:
            - node
          script:
            - mv .npmrc_config .npmrc
            - npm ci
            - npm test
